### ISSUE TITLE
Subtraction of 2 numbers in Python

### ISSUE THREAD

**Issue by Subhadas2000** [Audacity21/DSA-Codes#38]
WAP to subtract 2 numbers in Python

**Comment by Indrajeet-S** [comment]
I would like to contribute to this

**Comment by Indrajeet-S** [comment]
@Audacity21

**Comment by Audacity21** [comment]
> I would like to contribute to this
> 

Do it, I'll assign it to you

**Comment by Indrajeet-S** [comment]
@Audacity21 could you review it and let me know please

**Comment by Indrajeet-S** [comment]
@Audacity21 is this PR will successfully be counted in hactoberfest?

**Comment by Audacity21** [comment]
> @Audacity21 is this PR will successfully be counted in hactoberfest? 

Till now all the other PRs are counted as successfull. We have to wait for 7 days for final result.

**Comment by Indrajeet-S** [comment]
> > @Audacity21 is this PR will successfully be counted in hactoberfest?
> 
> Till now all the other PRs are counted as successfull. We have to wait for 7 days for final result.

Okay... Thanks
